"""empty message

Revision ID: fa488babce7b
Revises: 3ad3336a30e6
Create Date: 2021-05-22 00:37:02.874241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa488babce7b'
down_revision = '3ad3336a30e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'positions', sa.Column('_current_price', sa.Float(), nullable=True)
    )
    op.add_column(
        'positions',
        sa.Column('_current_price_last_check', sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', '_current_price_last_check')
    op.drop_column('positions', '_current_price')
    # ### end Alembic commands ###
