name: Tests

on:
  push:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up PostgreSQL
      run: |
        sudo systemctl start postgresql.service
        pg_isready
    - name: Create test user
      run: |
        sudo -u postgres psql --command="CREATE USER test_user PASSWORD 'somestrong'" --command="\du"
    - name: Create test database
      run: |
        sudo -u postgres createdb --owner=test_user test_llama
        PGPASSWORD=somestrong psql --username=test_user --host=localhost --list test_llama
    - name: Test with pytest
      env:
        ALPACA_UID: ${{ secrets.ALPACA_UID }}
        ALPACA_SECRET: ${{ secrets.ALPACA_SECRET }}
      run: |
        pytest
